#!/usr/bin/env python3
"""Analysis-only 3-minute vs 5-minute entry-timeframe comparison.

This is a SAME-SOURCE-OPPORTUNITY counterfactual, not a full alternate-history
market rescan. Source opportunities come from trade_history.jsonl (generated by
the historical bot). The purpose is to isolate what changes when those same
opportunities are evaluated/entered on 3m versus the next completed 5m candle.

Compared for 10-Aug-2026 and 11-Aug-2026:
  3M_BASELINE  current 3-minute timing, current exit stack
  3M_PLUS_A    3-minute timing + failed-development A
  5M_BASELINE  next completed 5-minute candle, current exit stack
  5M_PLUS_A    5-minute timing + failed-development A

Failed-development A:
  age >= 10 minutes AND MFE-from-entry < +0.15% AND current P/L < 0

Held constant:
- stored 15m ADX authorization/regime
- ADX <20 block, 20-<40 reverse, >=40 normal
- RSI extreme override after ADX gate
- 0.20% risk budget and 0.45% sizing geometry
- quantity capped at historical observed quantity (same replay limitation)
- sticky 5% daily-loss halt + aggregate open-risk guard
- 0.75% emergency stop
- hybrid / MAE / MFE / dead-trade / square-off stack
- cost model

5m timing approximation:
- take the first 5-minute boundary at/after the historical 3m order time;
- evaluate the 5m candle that has completed by that boundary;
- use the OPEN of that boundary's 1-minute bar as the market-entry proxy.
This avoids using future 5m information while acknowledging that exact tick fill
cannot be reconstructed from historical candles.

The loader retries transient empty Kite history and FAILS CLOSED if data is
incomplete. This script never imports/runs main.py and cannot place orders.
"""
from __future__ import annotations

import math
import time
from collections import Counter, defaultdict
from pathlib import Path

import pandas as pd

import replay_failed_development_variants_20260810_11 as fd

base = fd.base
current = fd.current
IST = fd.IST
DATES = ("2026-08-11", "2026-08-10")
MODES = ("3M_BASELINE", "3M_PLUS_A", "5M_BASELINE", "5M_PLUS_A")
OUT_SUMMARY = Path("/tmp/entry_timeframe_3m_vs_5m_summary.csv")
OUT_TRADES = Path("/tmp/entry_timeframe_3m_vs_5m_trades.csv")


def fetch_5m(kite, symbols, session_date):
    instruments = {
        x["tradingsymbol"]: x["instrument_token"]
        for x in kite.instruments("NSE")
        if x.get("instrument_type") == "EQ" and x.get("tradingsymbol") in symbols
    }
    missing = sorted(set(symbols) - set(instruments))
    if missing:
        raise RuntimeError("Missing NSE EQ instrument tokens: " + ", ".join(missing))

    warmup_date = (pd.Timestamp(session_date) - pd.Timedelta(days=8)).strftime("%Y-%m-%d")
    from_dt = pd.Timestamp(f"{warmup_date} 09:15", tz=IST).to_pydatetime()
    to_dt = pd.Timestamp(f"{session_date} 15:10", tz=IST).to_pydatetime()
    out = {}
    print(f"Fetching 5-minute history with integrity checks for {len(symbols)} symbols...")
    for idx, symbol in enumerate(sorted(symbols), 1):
        raw = fd._fetch_with_retry(
            kite,
            instruments[symbol],
            from_dt,
            to_dt,
            "5minute",
            80,
            f"{session_date} {symbol} 5minute",
        )
        out[symbol] = base.add_rsi_ema(raw)
        time.sleep(0.45)
        print(f"[5m {idx:02d}/{len(symbols):02d}] {symbol:<14} rows={len(out[symbol]):4d} OK")
    return out


def next_5m_boundary(ts):
    """First 5-minute boundary at or after the actual historical order time."""
    x = pd.Timestamp(ts)
    # Ceil exact boundary stays exact, which is what we want.
    return x.ceil("5min")


def latest_completed_5m(df5, decision_time):
    if df5 is None or df5.empty:
        return None
    eligible = df5.loc[df5["date"] + pd.Timedelta(minutes=5) <= decision_time]
    if eligible.empty:
        return None
    return eligible.iloc[-1]


def minute_entry_proxy(df1, decision_time):
    """Use the 1-minute bar open at the 5m decision boundary as fill proxy."""
    if df1 is None or df1.empty:
        return None
    minute_start = pd.Timestamp(decision_time).floor("min")
    exact = df1.loc[df1["date"] == minute_start]
    if exact.empty:
        later = df1.loc[df1["date"] >= minute_start]
        if later.empty:
            return None
        row = later.iloc[0]
    else:
        row = exact.iloc[0]
    return float(row["open"]), pd.Timestamp(row["date"])


def transform_op_for_mode(op, mode, minute, three, five):
    """Return an opportunity transformed to 3m or 5m timing/direction."""
    symbol = op["symbol"]
    if mode.startswith("3M"):
        df3 = three.get(symbol)
        row = base.indicator_row(df3, op["signal_start"])
        if row is None:
            return None, "MISSING_3M_INDICATOR"
        ema9 = float(row["ema9"])
        ema21 = float(row["ema21"])
        rsi = float(row["rsi14"]) if not pd.isna(row["rsi14"]) else None
        direction, base_direction, override = current.current_direction(
            op.get("adx"), ema9, ema21, rsi
        )
        new = dict(op)
        new.update(
            {
                "proposed_direction": direction,
                "proposed_base": base_direction,
                "rsi_override": override,
                "ema9": ema9,
                "ema21": ema21,
                "rsi": rsi,
                "timeframe": "3minute",
            }
        )
        return new, None

    df5 = five.get(symbol)
    decision_time = next_5m_boundary(op["order_time"])
    row5 = latest_completed_5m(df5, decision_time)
    if row5 is None:
        return None, "MISSING_5M_COMPLETED_CANDLE"
    proxy = minute_entry_proxy(minute.get(symbol), decision_time)
    if proxy is None:
        return None, "MISSING_5M_ENTRY_PROXY"
    entry_price, proxy_time = proxy

    ema9 = float(row5["ema9"])
    ema21 = float(row5["ema21"])
    rsi = float(row5["rsi14"]) if not pd.isna(row5["rsi14"]) else None
    direction, base_direction, override = current.current_direction(
        op.get("adx"), ema9, ema21, rsi
    )
    new = dict(op)
    new.update(
        {
            "entry": entry_price,
            "order_time": proxy_time,
            "signal_start": pd.Timestamp(row5["date"]),
            "proposed_direction": direction,
            "proposed_base": base_direction,
            "rsi_override": override,
            "ema9": ema9,
            "ema21": ema21,
            "rsi": rsi,
            "timeframe": "5minute",
            "source_3m_order_time": op["order_time"],
            "entry_delay_seconds": (proxy_time - op["order_time"]).total_seconds(),
        }
    )
    return new, None


def replay_mode(session_date, mode, opportunities, minute, three, five, square_off):
    transformed = []
    rejected_transform = []
    for op in opportunities:
        x, reason = transform_op_for_mode(op, mode, minute, three, five)
        if x is None:
            rejected_transform.append((op, reason))
        else:
            transformed.append(x)
    transformed.sort(key=lambda x: (x["order_time"], x["symbol"]))

    accepted = []
    rejected = list(rejected_transform)
    sticky_halt_time = None
    use_a = mode.endswith("PLUS_A")
    variant = fd.VARIANT_A if use_a else fd.BASELINE

    for op in transformed:
        now = op["order_time"]
        prior_legs = fd.completed_legs(accepted, now)
        realized = sum(float(leg["net"]) for leg in prior_legs)

        if sticky_halt_time is None:
            running = 0.0
            for leg in prior_legs:
                running += float(leg["net"])
                if running <= -fd.DAILY_LOSS_LIMIT:
                    sticky_halt_time = leg["time"]
                    break
        if sticky_halt_time is not None and now >= sticky_halt_time:
            rejected.append((op, "DAILY_LOSS_5PCT_STICKY_HALT"))
            continue

        adx = op.get("adx")
        if adx is not None and math.isfinite(float(adx)) and float(adx) < 20.0:
            rejected.append((op, "ADX_LT_20_BLOCK"))
            continue

        direction = op.get("proposed_direction")
        if direction not in {"BUY", "SELL"}:
            rejected.append((op, "DIRECTION_UNAVAILABLE"))
            continue

        per_share_risk = float(op["entry"]) * fd.STRATEGY_STOP_PCT / 100.0
        risk_qty = int(fd.RISK_AMOUNT / per_share_risk) if per_share_risk > 0 else 0
        qty = min(risk_qty, int(op["actual_qty"]))
        if qty <= 0:
            rejected.append((op, "QTY_ZERO_AT_0_2PCT_RISK"))
            continue

        open_now = fd.open_trades_at(accepted, now)
        if any(t["symbol"] == op["symbol"] for t in open_now):
            rejected.append((op, "SYMBOL_ALREADY_OPEN"))
            continue

        realized_loss = max(0.0, -realized)
        open_risk = sum(
            fd.strategy_risk_for(t["entry"], fd.remaining_qty_at(t, now))
            for t in open_now
        )
        proposed_risk = fd.strategy_risk_for(op["entry"], qty)
        aggregate = realized_loss + open_risk + proposed_risk
        if aggregate >= fd.DAILY_LOSS_LIMIT:
            rejected.append((op, "AGGREGATE_DAILY_RISK_GTE_BUDGET"))
            continue

        df1 = minute.get(op["symbol"])
        dfentry = three.get(op["symbol"]) if mode.startswith("3M") else five.get(op["symbol"])
        if df1 is None or df1.empty or dfentry is None or dfentry.empty:
            raise RuntimeError(f"DATA INTEGRITY FAILURE {session_date} {mode} {op['symbol']}")

        # For the 5m version, adverse_three should also respect the 5m entry
        # structure. The reused function only assumes that df has ema9/ema21 and
        # dates; its hard-coded 3-minute completion test would be wrong. We avoid
        # changing the native MAE rule semantics by constructing a 3m proxy only
        # for the native exit stack. Therefore this comparison primarily isolates
        # entry timing/direction; native exits stay on the historical 3m stack.
        exit_structure_df = three.get(op["symbol"])
        result = fd.replay_trade_variant(
            op,
            direction,
            qty,
            df1,
            exit_structure_df,
            variant,
            square_off,
        )
        if result is None:
            rejected.append((op, "NO_EXIT_HISTORY"))
            continue

        accepted.append(
            {
                **op,
                "direction": direction,
                "qty": qty,
                "risk_qty": risk_qty,
                "entry_time": now,
                "replay": result,
                "admission": {
                    "realized_pnl": realized,
                    "open_risk": open_risk,
                    "proposed_risk": proposed_risk,
                    "aggregate": aggregate,
                },
            }
        )

    legs = sorted(
        [leg for t in accepted for leg in t["replay"]["legs"]],
        key=lambda x: x["time"],
    )
    running = 0.0
    peak = 0.0
    max_dd = 0.0
    for leg in legs:
        running += float(leg["net"])
        peak = max(peak, running)
        max_dd = min(max_dd, running - peak)

    gross = sum(float(t["replay"]["gross"]) for t in accepted)
    costs = sum(float(t["replay"]["costs"]) for t in accepted)
    net = sum(float(t["replay"]["net"]) for t in accepted)
    wins = sum(1 for t in accepted if t["replay"]["net"] > 0)
    losses = sum(1 for t in accepted if t["replay"]["net"] < 0)
    delays = [
        float(t.get("entry_delay_seconds", 0.0))
        for t in accepted
        if t.get("timeframe") == "5minute"
    ]
    return {
        "date": session_date,
        "mode": mode,
        "accepted": accepted,
        "rejected": rejected,
        "trades": len(accepted),
        "wins": wins,
        "losses": losses,
        "win_rate": wins / len(accepted) * 100.0 if accepted else 0.0,
        "gross": gross,
        "costs": costs,
        "net": net,
        "return_pct": net / base.CAPITAL * 100.0,
        "max_dd": max_dd,
        "avg_5m_entry_delay_sec": sum(delays) / len(delays) if delays else 0.0,
        "variant_exits": sum(bool(t["replay"].get("variant_trigger")) for t in accepted),
        "rejections": Counter(reason for _, reason in rejected),
    }


def print_result(r):
    print("\n" + "=" * 110)
    print(f"{r['date']} | {r['mode']}")
    print("=" * 110)
    print(f"TRADES        : {r['trades']}")
    print(f"W/L           : {r['wins']} / {r['losses']} | WR {r['win_rate']:.2f}%")
    print(f"GROSS         : Rs {r['gross']:.2f}")
    print(f"COSTS         : Rs {r['costs']:.2f}")
    print(f"NET           : Rs {r['net']:.2f}")
    print(f"RETURN        : {r['return_pct']:.3f}%")
    print(f"MAX DD        : Rs {r['max_dd']:.2f}")
    print(f"EARLY A EXITS : {r['variant_exits']}")
    if r["mode"].startswith("5M"):
        print(f"AVG 5M DELAY  : {r['avg_5m_entry_delay_sec']:.1f} sec vs source 3m order")
    if r["rejections"]:
        print("REJECTIONS:")
        for reason, count in r["rejections"].most_common():
            print(f"  {reason:<38} {count}")


def main():
    print("Connecting to Kite for ANALYSIS-ONLY 3m vs 5m replay...")
    kite = base.get_kite_client()
    all_results = []
    detail = []

    for session_date in DATES:
        ctx = fd.configure_date(session_date)
        opportunities = base.group_history()
        if not opportunities:
            raise SystemExit(f"No source opportunities for {session_date}")
        symbols = sorted({op["symbol"] for op in opportunities})
        print(f"\nDAY {session_date} | source={len(opportunities)} | symbols={len(symbols)}")
        try:
            minute, three = fd.fetch_market_data_reliable(kite, symbols, session_date)
            five = fetch_5m(kite, symbols, session_date)
        except Exception as exc:
            raise SystemExit(
                f"DATA INTEGRITY BLOCK: {session_date} timeframe replay aborted: {exc}"
            ) from exc

        day_results = []
        for mode in MODES:
            r = replay_mode(
                session_date,
                mode,
                opportunities,
                minute,
                three,
                five,
                ctx.square_off,
            )
            day_results.append(r)
            all_results.append(r)
            print_result(r)

            for t in r["accepted"]:
                detail.append(
                    {
                        "date": session_date,
                        "mode": mode,
                        "entry_time": t["entry_time"],
                        "symbol": t["symbol"],
                        "direction": t["direction"],
                        "adx": t.get("adx"),
                        "qty": t["qty"],
                        "entry": t["entry"],
                        "net": t["replay"]["net"],
                        "gross": t["replay"]["gross"],
                        "costs": t["replay"]["costs"],
                        "mfe": t["replay"]["mfe"],
                        "mae": t["replay"]["mae"],
                        "exit_reasons": t["replay"]["reasons"],
                        "entry_delay_seconds": t.get("entry_delay_seconds", 0.0),
                    }
                )

        # Fail closed if the 3m baseline no longer resembles the complete current replay.
        three_baseline = next(x for x in day_results if x["mode"] == "3M_BASELINE")
        if session_date == "2026-08-11" and three_baseline["trades"] < 15:
            raise SystemExit(
                "REPLAY INTEGRITY BLOCK: complete Aug-11 3m baseline reconstructed fewer than 15 trades."
            )

    print("\n" + "#" * 110)
    print("TWO-DAY TIMEFRAME COMPARISON")
    print("#" * 110)
    totals = {}
    for mode in MODES:
        rows = [x for x in all_results if x["mode"] == mode]
        totals[mode] = {
            "trades": sum(x["trades"] for x in rows),
            "wins": sum(x["wins"] for x in rows),
            "losses": sum(x["losses"] for x in rows),
            "gross": sum(x["gross"] for x in rows),
            "costs": sum(x["costs"] for x in rows),
            "net": sum(x["net"] for x in rows),
            "max_dd_worst_day": min(x["max_dd"] for x in rows),
        }
        t = totals[mode]
        wr = t["wins"] / t["trades"] * 100.0 if t["trades"] else 0.0
        print(
            f"{mode:<12} trades={t['trades']:<3} W/L={t['wins']}/{t['losses']} "
            f"WR={wr:>6.2f}% gross=Rs {t['gross']:>8.2f} costs=Rs {t['costs']:>7.2f} "
            f"NET=Rs {t['net']:>8.2f} return={t['net']/base.CAPITAL*100:>7.3f}%"
        )

    print("\nDIRECT COMPARISONS")
    print(
        f"5M baseline minus 3M baseline : Rs "
        f"{totals['5M_BASELINE']['net'] - totals['3M_BASELINE']['net']:+.2f}"
    )
    print(
        f"3M + A minus 3M baseline      : Rs "
        f"{totals['3M_PLUS_A']['net'] - totals['3M_BASELINE']['net']:+.2f}"
    )
    print(
        f"5M + A minus 5M baseline      : Rs "
        f"{totals['5M_PLUS_A']['net'] - totals['5M_BASELINE']['net']:+.2f}"
    )

    best = max(MODES, key=lambda m: totals[m]["net"])
    print(f"BEST TWO-DAY MODE BY NET      : {best} | Rs {totals[best]['net']:.2f}")
    print("DEPLOYMENT                    : NONE — ANALYSIS ONLY")

    pd.DataFrame(
        [
            {
                "date": r["date"],
                "mode": r["mode"],
                "trades": r["trades"],
                "wins": r["wins"],
                "losses": r["losses"],
                "win_rate": r["win_rate"],
                "gross": r["gross"],
                "costs": r["costs"],
                "net": r["net"],
                "return_pct": r["return_pct"],
                "max_dd": r["max_dd"],
                "variant_exits": r["variant_exits"],
                "avg_5m_entry_delay_sec": r["avg_5m_entry_delay_sec"],
            }
            for r in all_results
        ]
    ).to_csv(OUT_SUMMARY, index=False)
    pd.DataFrame(detail).to_csv(OUT_TRADES, index=False)

    print("\nFILES")
    print(f"  {OUT_SUMMARY}")
    print(f"  {OUT_TRADES}")


if __name__ == "__main__":
    main()
